/**
 * Derived types for the idempotency-key contract every mutating endpoint carries.
 *
 * WHAT THIS MODULE IS
 *
 * Every type exported below is produced by `z.infer` over a schema that
 * `../schemas/idempotency.js` exports, or by a derivation over such an inferred
 * type — an `Extract`, an `Exclude`, a `keyof`, a `typeof`, an `infer`
 * extraction. There is no schema here, no runtime value and no hand-written
 * shape. Nothing in this file survives compilation: it emits declarations and
 * nothing else, which is why the package declares itself free of side effects
 * and why the coverage configuration excludes this directory from measurement
 * rather than reporting it at zero.
 *
 * The consequence worth stating plainly is that this module cannot drift. A
 * shape has exactly one definition — the schema — and a type inferred from that
 * definition changes when the definition changes. An `interface` restating a
 * schema's shape would be a second definition of one contract, and a second
 * definition is the thing that drifts, so none appears below. That discipline is
 * the same one the single-implementation rule imposes on the component
 * contracts: one contract, one place, extended rather than forked.
 *
 * WHERE THE CANONICAL TYPE OF EACH SCHEMA LIVES
 *
 * The schema module already exports a derived type for every schema it declares,
 * and for three of them it must: the key schema's own type, the envelope
 * schema's type and the result union's type are what let the two schema
 * factories declare explicit return types instead of inferred ones, which is the
 * difference between a shape change failing the build and a shape change
 * silently widening. Those declarations are load-bearing where they are and
 * cannot be moved here.
 *
 * So this module does not restate them, and above all does not re-export them
 * under the same names: the package barrel flattens every module into one
 * namespace, and one name arriving from two modules is a compile error in a file
 * neither module owns. What lives next door, and is imported from there:
 *
 *   - the key's own type, and the schema type the envelope factory spells its
 *     return with;
 *   - the inbound header bag's parsed type;
 *   - the stored request fingerprint's type;
 *   - the envelope's schema type and its parsed type, both generic over a
 *     route's payload schema;
 *   - the outcome union, the absolute-instant type, the result union's schema
 *     type and its parsed type, and the conflict body's type;
 *   - the rejection-code union.
 *
 * What lives here is the remainder — the derived surface the schema module
 * leaves underived. Four kinds, and no fifth:
 *
 *   - the transport name the key travels under, as a type, so an outbound header
 *     bag can be keyed by the canonical name rather than by convention;
 *   - the rejection registry's key vocabulary, plus a partition of the code
 *     union into the codes a caller can correct and the codes that report a
 *     contract defect;
 *   - the envelope's domain half, named apart from the transport half it is
 *     deliberately nested beside;
 *   - the result union's two cases, named individually so a call site can say
 *     which one it is holding, and the result value both cases carry.
 *
 * WHY THE TWO RESULT CASES STAY APART
 *
 * A fresh execution and a replay are two shapes, not one shape with a flag. Only
 * a replay can say when the original ran, so a single flat object would have to
 * make that instant optional and would then admit a fresh execution carrying
 * one — a state that cannot occur. Collapsing the two is worse than untidy: it
 * is what makes a replayed mutation indistinguishable from a fresh one at the
 * call site, and a client that cannot tell them apart cannot leave a retry loop.
 * The schema draws the distinction with a discriminated union; the types below
 * name each side of it and merge nothing, exactly as the single-implementation
 * rule requires of two contracts that resemble each other.
 *
 * WHAT THESE TYPES ARE NOT
 *
 * They are shapes. They are not a trust boundary, and no value acquires any
 * property by being annotated with one.
 *
 *   - **The key is generated by the client, so it is caller-supplied data, and
 *     it confers no authority whatsoever.** It is never an authorization input,
 *     and it identifies neither the actor nor the workspace. Every mutation is
 *     authorized independently on the server at its point of execution, against
 *     the acting session and the specific target object, at the chokepoint in
 *     `apps/api/src/authz/guard.ts`. A replayed request is **re-authorized**
 *     rather than trusted for having been seen before: a recorded outcome is a
 *     memo of a decision already taken, never a standing grant to take it again.
 *     Holding a well-formed key is not evidence of permission, and nothing below
 *     declares a field an actor or a workspace could be read out of — that
 *     absence is the contract, because a field that could carry an identifier is
 *     a field a caller could set.
 *   - **Validation happens elsewhere.** A value typed as anything below has
 *     satisfied the compiler, which says nothing about whether it satisfied the
 *     schema. A key arriving over the wire is parsed by the schema next door,
 *     whose well-formedness check is delegated to the one canonical guard in
 *     `../util/ulid.js` — so neither that module nor this one declares a
 *     pattern, an alphabet or a length of its own, and a second copy of the
 *     encoding rule cannot drift from the generator that mints these values.
 *   - **No uniqueness is enforced by a type.** The send path's invariant is the
 *     conversation-and-client-identifier pair, and it is enforced by a database
 *     constraint in `packages/db/prisma/schema.prisma`, which is the only place
 *     it can be enforced rather than hoped for. A client may legitimately send
 *     one key twice — that is the entire point of the mechanism — so nothing
 *     below asserts that a key is unique, and no comment should be read as
 *     implying it.
 *   - **No behaviour is asserted, and no window is stated.** Whether a route
 *     executes, replays or rejects is decided by the route against the durable
 *     store; how long a record survives is a configured value owned by the
 *     shared configuration surface and consumed by reference. No duration and no
 *     bound appears in this file, in a type or in a comment.
 *
 * This module introduces no mutation and no projection of its own, so it owes no
 * denial test. The behaviour these shapes describe — first use, exact replay,
 * and reuse against a different request — is proved per route in
 * `apps/api/test/integration/idempotency`, which is where a test asserting a
 * server-side denial belongs.
 *
 * A NOTE ON OPTIONAL MEMBERS — OMIT THE PROPERTY, DO NOT ASSIGN IT
 *
 * Every member this contract declares is required, and that is deliberate rather
 * than incidental: an optional recorded instant on one flat object is precisely
 * the shape the result union exists to avoid. So the usual caution has one
 * narrow application here, and one only — a route is free to hand the envelope
 * factory a payload schema that is itself optional, and the envelope's payload
 * member is then optional too.
 *
 * Where that happens, omit the property rather than assigning it the absent
 * case. The two forms are not interchangeable, and the difference is observable
 * rather than stylistic: the schema's own output for an absent optional omits
 * the key, a presence test by key disagrees with the two forms while both carry
 * the same nothing, and serialising drops an assigned key so a value that has
 * crossed the wire and one that has not become unequal by key set. The
 * exact-optional-property-types setting refuses the absent case only where the
 * value type excludes it, and an inferred optional's value type includes it, so
 * the compiler accepts both spellings and cannot help here.
 *
 * HOW TO CONSUME IT
 *
 * Through the package barrel — `@relay/shared` — and not by path. Inside this
 * package the sibling schema module is reached relatively, because that is how a
 * package is built; from outside, the barrel is the only entry point. These
 * shapes are consumed by the server, by the browser client's request helper in
 * `apps/web/src/api/idempotency.ts` and by the end-to-end suite alike, so no
 * framework type appears below — a server-side header type would be correct in
 * one of those three places and wrong in the other two.
 */
import type { z } from 'zod';
import type {
  IDEMPOTENCY_FIRST_EXECUTED_AT_FIELD,
  IDEMPOTENCY_KEY_HEADER,
  IDEMPOTENCY_OUTCOME_FIELD,
  IDEMPOTENCY_PAYLOAD_FIELD,
  IDEMPOTENCY_REJECTION,
  IDEMPOTENCY_RESULT_FIELD,
  IdempotencyInstant,
  IdempotencyOutcome,
  IdempotencyRejectionCode,
  IdempotentResult,
  MutationEnvelope,
} from '../schemas/idempotency.js';

/* -------------------------------------------------------------------------- */
/* The name the key travels under                                             */
/* -------------------------------------------------------------------------- */

/**
 * The canonical header name, as a type.
 *
 * **Not the same thing as the parsed header bag**, which the schema module
 * already types. That type describes an *inbound* request after parsing, where
 * unknown headers are stripped and the key is all that survives. An *outbound*
 * header bag is assembled by hand — the client's request helper builds one, a
 * test builds one — and no schema types the assembly. This is what types it:
 *
 * ```ts
 * const headers: Record<IdempotencyKeyHeaderName, IdempotencyKey> = { ... };
 * ```
 *
 * Written that way, the property name is checked against the one declaration of
 * the header's spelling rather than against a caller's memory of it. A literal
 * in that position compiles just as happily and is exactly the second
 * declaration the single-definition discipline exists to prevent: two spellings
 * only have to disagree once — on a typo, on a hyphen — for a route to stop
 * being idempotent while every test still passes.
 *
 * Derived with `typeof` over the exported constant, so it is the constant's type
 * rather than a copy of its value. Nothing here re-exports the constant itself:
 * this module is type-only, and a consumer that needs the runtime string imports
 * it from the schema module through the barrel.
 */
export type IdempotencyKeyHeaderName = typeof IDEMPOTENCY_KEY_HEADER;

/* -------------------------------------------------------------------------- */
/* Rejection: the registry's keys, and a partition of the code union          */
/* -------------------------------------------------------------------------- */

/*
 * The schema module declares its rejection codes once, as a registry, and builds
 * the code schema from that registry — so the enumerable set and the wire union
 * are two views of one declaration. The union is exported next door. What is not
 * exported anywhere is the registry's own *key* vocabulary, and the partition of
 * the union that separates a caller's mistake from a contract defect. Both are
 * derived below rather than listed, because a list beside a declaration is the
 * thing that is wrong after the declaration changes.
 */

/**
 * The registry's key vocabulary: the names each rejection is known by internally,
 * as opposed to the codes that cross the wire.
 *
 * Its value is exhaustiveness. A lookup written as
 * `Record<IdempotencyRejectionKind, T>` — a status per rejection on the server, a
 * copy key per rejection on the client — cannot be missing an entry, so adding a
 * rejection to the registry breaks every lookup that has not accounted for it.
 * That is the opposite of what a lookup keyed by anything else does, which is to
 * fall through silently and report a rejection as though it were a success.
 *
 * Derived with `keyof typeof`, so the vocabulary is read off the registry the
 * code schema is itself built from.
 */
export type IdempotencyRejectionKind = keyof typeof IDEMPOTENCY_REJECTION;

/**
 * The rejections a caller provoked and a caller can correct: the header absent,
 * its value not a well-formed key, or the key reused against a different request.
 *
 * Named as a set because the three share a remedy shape — change the request and
 * try again — while the remainder do not. A surface reporting one of these is
 * telling somebody something actionable; a surface reporting one of the others is
 * reporting that the product is misbehaving, and conflating the two produces the
 * familiar defect of asking a person to fix a fault that is not theirs.
 *
 * Narrowed with `Extract` over the code union rather than read straight off the
 * registry, which is deliberate and not ceremony: `Extract` makes the result
 * provably a subset of the codes the schema actually accepts. Were the code
 * schema ever built from something other than this registry, this resolves to
 * nothing assignable and the mistake surfaces here, instead of typing a string
 * that no parser will ever produce.
 */
export type IdempotencyRequestRejectionCode = Extract<
  IdempotencyRejectionCode,
  (typeof IDEMPOTENCY_REJECTION)['missing' | 'malformed' | 'conflict']
>;

/**
 * The rejections that report a contract defect rather than bad input: a stored
 * fingerprint that is not of the shape the contract fixes, and a response that
 * does not match the contract at the boundary a client validates it on.
 *
 * Neither is a caller's fault and neither is a caller's to fix. Both are worth
 * surfacing loudly rather than folding into a generic failure, because each names
 * a specific side that has drifted — the recording path, or the responding
 * server.
 *
 * Defined as the complement rather than as its own list, so the two narrowings
 * **partition** the union exhaustively: every code is in exactly one of them, and
 * a code added to the registry without touching this file lands here — on the
 * side that says "the product is at fault", which is the safer default of the two
 * and the one that gets noticed.
 */
export type IdempotencyContractRejectionCode = Exclude<
  IdempotencyRejectionCode,
  IdempotencyRequestRejectionCode
>;

/* -------------------------------------------------------------------------- */
/* The envelope's domain half                                                 */
/* -------------------------------------------------------------------------- */

/**
 * What a route's payload becomes once the envelope has been parsed: the domain
 * half, without the key beside it.
 *
 * The envelope nests a route's payload rather than merging a key field into it,
 * so that the transport concern never reaches the domain layer's signatures. This
 * type is what makes that separation sayable. A service function takes the
 * payload half and names it, instead of reaching through the envelope type at
 * every call site or — worse — accepting the whole envelope and quietly becoming
 * a function that knows about headers.
 *
 * **The extraction matches an optional property on purpose.** A route may compose
 * the envelope around a payload schema that is itself optional, and the envelope's
 * payload member is then optional too. A matcher that demanded a required
 * property would resolve to nothing assignable in exactly that case, which is a
 * silent failure: the type would compile and be useless. Matching optionally
 * covers both, and where the payload is optional the property is **omitted**
 * rather than assigned the absent case — see the note on optional members above.
 */
export type MutationEnvelopePayload<TPayload extends z.ZodType> =
  MutationEnvelope<TPayload> extends { [K in typeof IDEMPOTENCY_PAYLOAD_FIELD]?: infer TValue }
    ? TValue
    : never;

/* -------------------------------------------------------------------------- */
/* The result union's two cases, named individually                           */
/* -------------------------------------------------------------------------- */

/*
 * A route that has resolved a key answers with one of two shapes, and a consumer
 * that has branched on which one it received wants a name for the branch it is
 * in. The first three types below supply those names by narrowing the union the
 * schema declares — never by restating a member — so a case gains a field exactly
 * when its schema does, and neither case can quietly acquire the other's shape.
 * The fourth names the result value both cases carry, which is a different thing
 * and is documented as such where it is declared.
 *
 * Two narrowing criteria are available and they agree. The union's declared
 * discriminant is the outcome, and the generic below narrows on it. The two cases
 * also differ structurally: only the replayed case carries the instant the
 * original was recorded at, because only a replay has an original to report. The
 * two named cases narrow on that instant, which lets them name a case without
 * writing either outcome value down a second time — the values belong to the
 * schema, and this module reads them rather than repeating them.
 */

/**
 * The result case, or cases, carrying a given outcome.
 *
 * Narrowed from the union on its own declared discriminant, so passing an outcome
 * the union does not contain resolves to nothing assignable and the mistake
 * surfaces where it is written rather than where the value is used. It accepts a
 * union of outcomes as readily as a single one, resolving to the union of the
 * cases that match — which is how a caller says "either case" without abandoning
 * the union.
 *
 * This is the general form. The two specific cases have their own names below,
 * and a consumer should reach for those unless the outcome is itself a parameter.
 */
export type IdempotentResultOfOutcome<
  TResult extends z.ZodType,
  TOutcome extends IdempotencyOutcome,
> = Extract<IdempotentResult<TResult>, Record<typeof IDEMPOTENCY_OUTCOME_FIELD, TOutcome>>;

/**
 * The case reporting that the request was authorized, executed and recorded now.
 *
 * It carries the route's result and no instant, because there is no earlier
 * execution to date. A consumer holding this knows the write happened on this
 * request — which is the only circumstance in which anything downstream of the
 * mutation should be treated as newly caused: a notification worth sending, an
 * optimistic row worth reconciling against a first acknowledgement.
 *
 * Derived as the complement of the replayed case, so the two exhaust the union
 * and neither can drift into the other.
 */
export type IdempotentExecution<TResult extends z.ZodType> = Exclude<
  IdempotentResult<TResult>,
  Record<typeof IDEMPOTENCY_FIRST_EXECUTED_AT_FIELD, IdempotencyInstant>
>;

/**
 * The case reporting that the request had already been executed, and that this is
 * the recorded result of that earlier execution.
 *
 * It carries the same result the first execution returned — not a recomputation
 * that resembles it — together with the absolute instant the original was
 * recorded at. A route that recomputes on replay has not implemented this case;
 * it has implemented a second execution that reports itself as a replay.
 *
 * A consumer holding this knows the work is already settled and must not repeat
 * it, and must not treat it as newly caused: sending a notification again here is
 * how one retry becomes two announcements of one event. The instant is what lets
 * a client tell a retry it issued moments ago from a key it is reusing from far
 * earlier, without being told how long a record survives.
 *
 * Narrowed on the recorded instant, which the first-execution case does not
 * carry. The criterion is structural and the result is identical to narrowing on
 * the discriminant.
 */
export type IdempotentReplay<TResult extends z.ZodType> = Extract<
  IdempotentResult<TResult>,
  Record<typeof IDEMPOTENCY_FIRST_EXECUTED_AT_FIELD, IdempotencyInstant>
>;

/**
 * The route's own result, as carried by either case.
 *
 * For the consumer that has already branched, or has deliberately decided it does
 * not need to: a reconciliation that is complete either way takes this rather
 * than reaching into whichever case it happens to hold. Note the order — branch
 * first if the branch matters, then flatten. Flattening in order to *avoid*
 * branching is how a replay comes to be handled as a fresh execution, which is
 * the one mistake this whole contract exists to prevent.
 *
 * That this resolves to a single type at all is the contract's substantive
 * guarantee rather than a convenience: both cases carry the *same* result,
 * because a replay returns what the original execution returned. Were the two
 * ever to diverge, this would widen to a union and every consumer would be made
 * to acknowledge the difference — which is the right outcome, and the reason this
 * is derived from the union rather than from one case.
 */
export type IdempotentResultValue<TResult extends z.ZodType> =
  IdempotentResult<TResult> extends { [K in typeof IDEMPOTENCY_RESULT_FIELD]?: infer TValue }
    ? TValue
    : never;
